name: testmac

on:
  workflow_dispatch:

jobs:
  build_macos:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Build
        run: |
          cd ~/work/github_action_test/github_action_test
          python3 ./build.py && python3 -c "import shutil; shutil.make_archive('./mydist', 'zip', './dist/main')"
      